### PR TITLE
QGIS3 support

### PR DESCRIPTION
**Pull request by ChrFr**
Hi,

i adapted the plugin to run in QGIS3. I did not test the results, but it runs and should work as before.

best regards,
Christoph

### CODE REVIEW

**Comment by simgislab** [comment]
thanks

will it continue to work under 2.x?

**Comment by ChrFr** [comment]
Unfortunatelly it won't work with QGIS 2.x. maybe i should have made a new branch instead of making the changes in the master branch.

**Comment by denor81** [comment]
Hi! I have error message when try create poly file from polygon type. Multipolygon is ok. http://prntscr.com/owxbeh

**Comment by simgislab** [comment]
released a QGIS 3 version

**Pull request closed without merging**
